basic_settings:
  site_title: pierluisvona.it
  favicon_image: /images/favicon.png

header_settings:
  logo_image: /images/typo.png
  logo_width: 150

menu_settings:
  menu_items:
    - title: 'shootings'
      url: '/'
    - title: 'projects'
      url: '/blog'
    - title: 'about me'
      url: '/about'

footer_settings:
  footer_tagline: pierluisvona.it // photography portfolio
  logo_image: /images/logo.png
  logo_width: 60

grid_settings:
  overlay_opacity: 0.8
  grid_spacing: 20
  content_alignment: top

contact_settings:
  form_action: ''
  confirmation_url: ''
  email_subject: ''
  send_button_text: ''

social_settings:
  instagram_url: 'https://www.instagram.com/pierluisvona/'
  github_url: 'https://github.com/PierLuisVona'
  linkedin_url: 'https://www.linkedin.com/in/pierluigi-vona-30415812b/'

color_settings:
  background_color: '#ffffff'
  background_alt_color: '#ABCDEB'
  text_dark_color: '#2A2F36'
  text_medium_color: '#6C7A89'
  text_light_color: '#ABB7B7'
  accent_color: '#3f7893'
  border_color: '#dddddd'
  overlay_background_color: '#3f7893'
  overlay_text_color: '#ffffff'
  overlay_accent_color: '#2A2F36'
  error_color: '#D64541'

font_settings:
  font_embed: '<link href="https://fonts.googleapis.com/css?family=Raleway:300,400,600,700" rel="stylesheet">'
  title_font: '"Raleway", sans-serif'
  body_font: '"Raleway", sans-serif'
  regular_weight: 300
  bold_weight: 500
  site_title:
    small_size: 22
    medium_size: 26
    large_size: 30
    weight: 500
    letter_spacing: -0.02
  menu:
    small_size: 30
    medium_size: 14
    large_size: 15
    weight: 500
    letter_spacing: 0
  grid_item_title:
    small_size: 22
    medium_size: 24
    large_size: 28
    weight: 700
    letter_spacing: -0.02
  grid_item_subtitle:
    small_size: 13
    medium_size: 15
    large_size: 17
    weight: 500
    letter_spacing: 0
  h1:
    small_size: 25
    medium_size: 35
    large_size: 45
    weight: 700
    letter_spacing: -0.02
    line_height: 1.2
  h2:
    small_size: 22
    medium_size: 30
    large_size: 35
    weight: 600
    letter_spacing: -0.02
    line_height: 1.2
  h3:
    small_size: 22
    medium_size: 25
    large_size: 30
    weight: 500
    letter_spacing: -0.02
    line_height: 1.3
  h4:
    small_size: 17
    medium_size: 22
    large_size: 22
    weight: 500
    letter_spacing: 0
    line_height: 1.6
  h5:
    small_size: 17
    medium_size: 20
    large_size: 20
    weight: 500
    letter_spacing: 0
    line_height: 1.6
  h6:
    small_size: 17
    medium_size: 20
    large_size: 20
    weight: 500
    letter_spacing: 0
    line_height: 1.6
  p:
    small_size: 15
    medium_size: 17
    large_size: 19
    weight: 300
    letter_spacing: 0
    line_height: 1.6
  blockquote:
    small_size: 25
    medium_size: 35
    large_size: 45
    weight: 300
    letter_spacing: -0.02
    line_height: 1.6
  buttons:
    weight: 500
    letter_spacing: 0

advanced_settings:
  ajax_loading: true
  analytics_code: ""
  custom_styles: ""
  header_js: ""
  footer_js: ""
